name: bColoredChat
main: com.beecub.bColoredChat.bColoredChat
version: 2.0.0
author: beecub
description: >
             Chat Colors
commands:
  useColor:
    description: Set own chat color
    usage: |
           /<command> [&black&|&darkblue&|&darkgreen&|&darkaqua&|&darkred&|&purple&|&gold&|&gray&|&darkgray&|&blue&|&green&|&aqua&|&red&|&pink&|&yellow&|&white&]
  setColor:
    description: Set player chat color
    usage: |
           /<command> [name] [colorcode]
  clearColor:
    description: Remove player chat color
    usage: |
           /<command> [name]
  randomColor:
    description: random text
    usage: |
           /<command> [text]
  rainbowColor:
    description: rainbow text
    usage: |
           /<command> [text]