name: bColoredChat
main: com.beecub.bColoredChat.bColoredChat
version: 2.1.0
author: beecub
description: >
             Chat Colors
commands:
  useColor:
    description: Set own chat color
    usage: |
           /<command> [ColorCode]
  setColor:
    description: Set player chat color
    usage: |
           /<command> [name] [colorcode]
  clearColor:
    description: Remove player chat color
    usage: |
           /<command> [name]
  randomColor:
    description: random text
    usage: |
           /<command> [text]
  rainbowColor:
    description: rainbow text
    usage: |
           /<command> [text]
  showColors:
    description: Show available colors
    usage: |
           /<command>